(ai-economist2) ettore@UBU21:~/Tesi/ai-economist-ppo-decision-tree/ai-economist/tutorials/rllib==2.0.0$ python3 training_2_algos.py 
/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  _nlv = LooseVersion(_np_version)
/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/setuptools/_distutils/version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/pandas/compat/numpy/function.py:120: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(__version__) >= LooseVersion("1.17.0"):
/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/matplotlib/__init__.py:202: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(module.__version__) < minver:
/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/setuptools/_distutils/version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/matplotlib/backend_bases.py:59: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(PILLOW_VERSION) >= "3.4":
/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/setuptools/_distutils/version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
Inside covid19_components.py: 0 GPUs are available.
No GPUs found! Running the simulation on a CPU.
Inside covid19_env.py: 0 GPUs are available.
No GPUs found! Running the simulation on a CPU.
2022-09-14 12:06:55,310 INFO worker.py:1518 -- Started a local Ray instance.
2022-09-14 12:06:56,778 seed (final): 42944000
2022-09-14 12:06:56,831 INFO algorithm.py:1872 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
2022-09-14 12:06:56,831 WARNING deprecation.py:48 -- DeprecationWarning: `metrics_smoothing_episodes` has been deprecated. Use `metrics_num_episodes_for_smoothing` instead. This will raise an error in the future!
2022-09-14 12:06:56,832 INFO algorithm.py:354 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
Traceback (most recent call last):
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 425, in setup
    logdir=self.logdir,
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 127, in __init__
    validate=trainer_config.get("validate_workers_after_construction"),
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 269, in add_workers
    self.foreach_worker(lambda w: w.assert_healthy())
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 391, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=220231, ip=192.168.0.24, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7ff6965f9b10>)
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 617, in __init__
    seed=seed,
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1790, in _build_policy_map
    merged_conf,
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/policy/policy_map.py", line 131, in create_policy
    self.seed,
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/utils/policy.py", line 72, in create_policy_for_framework
    observation_space, action_space, merged_config
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/algorithms/ppo/ppo_tf_policy.py", line 89, in __init__
    existing_model=existing_model,
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py", line 93, in __init__
    ) = self._init_action_fetches(timestep, explore)
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py", line 619, in _init_action_fetches
    dist_inputs, self._state_out = self.model(self._input_dict)
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/models/modelv2.py", line 259, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "/home/ettore/Tesi/ai-economist-ppo-decision-tree/ai-economist/tutorials/rllib==2.0.0/tf_models.py", line 306, in forward
    for t in self._extract_input_list(input_dict["obs"])
  File "/home/ettore/Tesi/ai-economist-ppo-decision-tree/ai-economist/tutorials/rllib==2.0.0/tf_models.py", line 306, in <listcomp>
    for t in self._extract_input_list(input_dict["obs"])
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/policy/rnn_sequencing.py", line 197, in add_time_dimension
    axis=0,
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1969, in _create_c_op
    raise ValueError(e.message)
ValueError: Shape must be rank 2 but is rank 1 for '{{node agent_policy_wk2/concat}} = ConcatV2[N=3, T=DT_INT32, Tidx=DT_INT32](agent_policy_wk2/ExpandDims, agent_policy_wk2/ExpandDims_1, agent_policy_wk2/strided_slice_6, agent_policy_wk2/concat/axis)' with input shapes: [1,?], [1,?], [1], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "training_2_algos.py", line 392, in <module>
    trainerAgents, trainerPlanner = build_trainer(run_config)
  File "training_2_algos.py", line 183, in build_trainer
    * trainer_config.get("num_envs_per_worker"),
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 308, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ettore/anaconda3/envs/ai-economist2/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 443, in setup
    raise e.args[0].args[2]
ValueError: Shape must be rank 2 but is rank 1 for '{{node agent_policy_wk2/concat}} = ConcatV2[N=3, T=DT_INT32, Tidx=DT_INT32](agent_policy_wk2/ExpandDims, agent_policy_wk2/ExpandDims_1, agent_policy_wk2/strided_slice_6, agent_policy_wk2/concat/axis)' with input shapes: [1,?], [1,?], [1], [].